### ISSUE TITLE
zero found flows not handled appropriately

### ISSUE THREAD

**Issue by mbertheau** [flowdock/hubot-flowdock#70]
I'm setting up a new hubot and apparently I'm having troubles with the flows, since it found zero. This is not handled well:

```
[Fri Jan 16 2015 10:46:57 GMT+0100 (CET)] INFO Found 0 flows.
[Fri Jan 16 2015 10:46:57 GMT+0100 (CET)] INFO Connecting to Flowdock as user undefined (id 123993).
[Fri Jan 16 2015 10:46:57 GMT+0100 (CET)] ERROR TypeError: Cannot call method 'toLowerCase' of undefined
  at Flowdock.run (/home/markus/src/machtbot/node_modules/hubot-flowdock/src/flowdock.coffee:147:10, <js>:223:67)
  at Request.Session.flows [as _callback] (/home/markus/src/machtbot/node_modules/hubot-flowdock/node_modules/flowdock/lib/flowdock.js:69:53)
  at Request.init.self.callback (/home/markus/src/machtbot/node_modules/hubot-flowdock/node_modules/flowdock/node_modules/request/main.js:122:22)
```

**Comment by Mumakil** [comment]
Thanks for reporting! I fixed both this and #71.
