### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by victorhooi** [flowdock/hubot-flowdock#79]
We're using hubot-flowdock 0.7.5 with hubot 2.12.0.

Recently, we've been getting these error messages, and the Hubot instance stops responding afterwards, and needs to be restarted:

```
[Wed May 06 2015 07:19:34 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'id' of undefined
  at Stream.<anonymous> (/home/ubuntu/foo-glados/node_modules/hubot-flowdock/src/flowdock.coffee:69:9, <js>:130:52)
  at Stream.emit (events.js:95:17)
  at JSONStream.<anonymous> (/home/ubuntu/foo-glados/node_modules/hubot-flowdock/node_modules/flowdock/lib/stream.js:67:28)
  at JSONStream.emit (events.js:95:17)
  at JSONStream.write (/home/ubuntu/foo-glados/node_modules/hubot-flowdock/node_modules/flowdock/lib/json_stream.js:30:14)
  at Request.ondata (stream.js:51:26)
  at Request.emit (events.js:95:17)
  at IncomingMessage.<anonymous> (/home/ubuntu/foo-glados/node_modules/hubot-flowdock/node_modules/flowdock/node_modules/request/request.js:1108:12)
  at IncomingMessage.emit (events.js:95:17)
  at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
  at IncomingMessage.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at IncomingMessage.Readable.push (_stream_readable.js:128:10)
  at HTTPParser.parserOnBody [as onBody] (http.js:143:22)
  at CleartextStream.socketOnData [as ondata] (http.js:1588:20)
  at CleartextStream.read [as _read] (tls.js:514:12)
  at CleartextStream.Readable.read (_stream_readable.js:341:10)
  at EncryptedStream.write [as _write] (tls.js:369:25)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at EncryptedStream.Writable.write (_stream_writable.js:183:11)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at Socket.pipeOnReadable (_stream_readable.js:643:5)
  at Socket.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at emitReadable (_stream_readable.js:423:5)
  at readableAddChunk (_stream_readable.js:166:9)
  at Socket.Readable.push (_stream_readable.js:128:10)
  at TCP.onread (net.js:529:21)
```

**Comment by Mumakil** [comment]
Sorry about the issue! We had a bug where a certain message type was malformed and this caused the hubot adapter to throw an error. The underlying issue has been fixed but I think we'll need to add some precautions to the adapter to prevent it from crashing on issues like this.
