### ISSUE TITLE
Error on buffertools/node-gyp compile on adding hubot-flowdock to dependencies.

### ISSUE THREAD

**Issue by chris-sanders-dot-org** [flowdock/hubot-flowdock#86]
I'm getting the below error when attempting to add hubot-flowdock as an adapter.  I tried the possible solutions found online, with no success.

I also opened a case with Rally support, which seems to have been forgotten.  816018

Thanks.

Error:
autobot@GIS07948:~/autobot$ bin/hubot

> buffertools@2.1.3 install /home/autobot/autobot/node_modules/buffertools
> node-gyp rebuild

make: Entering directory `/home/autobot/autobot/node_modules/buffertools/build'
  CXX(target) Release/obj.target/buffertools/buffertools.o
In file included from /home/autobot/.node-gyp/4.2.2/include/node/node.h:42:0,
                 from ../buffertools.cc:17:
/home/autobot/.node-gyp/4.2.2/include/node/v8.h:336:1: error: expected unqualified-id before ‘using’
/home/autobot/.node-gyp/4.2.2/include/node/v8.h:469:1: error: expected unqualified-id before ‘using’
/home/autobot/.node-gyp/4.2.2/include/node/v8.h:852:1: error: expected unqualified-id before ‘using’
../buffertools.cc:32:11: error: ‘v8::Handle’ has not been declared
../buffertools.cc:492:21: error: variable or field ‘RegisterModule’ declared void
../buffertools.cc:492:21: error: ‘Handle’ was not declared in this scope
../buffertools.cc:492:34: error: expected primary-expression before ‘>’ token
../buffertools.cc:492:36: error: ‘target’ was not declared in this scope
../buffertools.cc:506:1: error: ‘RegisterModule’ was not declared in this scope
make: *** [Release/obj.target/buffertools/buffertools.o] Error 1
make: Leaving directory `/home/autobot/autobot/node_modules/buffertools/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-29-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/autobot/autobot/node_modules/buffertools
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
autobot@0.0.0 /home/autobot/autobot
└─┬ hubot@2.17.0
  └── proxy-agent@2.0.0  extraneous

npm ERR! Linux 3.2.0-29-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.0
npm ERR! code ELIFECYCLE

npm ERR! buffertools@2.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buffertools@2.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buffertools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls buffertools
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/autobot/autobot/npm-debug.log

**Comment by peterdalydickson** [comment]
I've just installed a new hubot and got exactly the same error @chris-sanders-dot-org.

Did you ever get this resolved?
